/**
 * Created by wxun on 2023/3/30 18:16.
 * description: hotelTvTmpl 酒店源模板
 */

// 广东揭阳酒店源模板
const GDJY_HOTEL_TMPL = [
  { id: 1, name: "CCTV1" },
  { id: 2, name: "CCTV2" },
  { id: 3, name: "CCTV3" },
  { id: 4, name: "CCTV4" },
  { id: 5, name: "CCTV5" },
  { id: 45, name: "CCTV5+" },
  { id: 6, name: "CCTV6" },
  { id: 7, name: "CCTV7" },
  { id: 8, name: "CCTV8" },
  { id: 9, name: "CCTV9" },
  { id: 10, name: "CCTV10" },
  { id: 12, name: "CCTV12" },
  { id: 13, name: "CCTV13" },
  { id: 14, name: "CCTV14" },
  { id: 15, name: "CCTV15" },
  { id: 16, name: "CCTV16" },
  { id: 17, name: "CCTV17" },
  { id: 45, name: "北京卫视" },
  { id: 47, name: "东方卫视" },
  { id: 40, name: "广东卫视" },
  { id: 46, name: "深圳卫视" },
  { id: 48, name: "天津卫视" },
  { id: 57, name: "河北卫视" },
  { id: 54, name: "辽宁卫视" },
  { id: 59, name: "吉林卫视" },
  { id: 50, name: "黑龙江卫视" },
  { id: 44, name: "江苏卫视" },
  { id: 43, name: "浙江卫视" },
  { id: 55, name: "东南卫视" },
  { id: 58, name: "江西卫视" },
  { id: 49, name: "安徽卫视" },
  { id: 51, name: "湖北卫视" },
  { id: 42, name: "湖南卫视" },
  { id: 60, name: "广西卫视" },
  { id: 53, name: "贵州卫视" },
  { id: 52, name: "四川卫视" },
  { id: 18, name: "广东体育" },
  { id: 139, name: "广东经济科教" },
  { id: 68, name: "深圳都市" },
  { id: 18, name: "深圳电视剧" },
  { id: 70, name: "深圳体育健康" },
  { id: 67, name: "翡翠台" },
  { id: 32, name: "凤凰中文" },
  { id: 33, name: "凤凰资讯" },
  { id: 34, name: "凤凰深圳旁边" },
  { id: 35, name: "TVB星河" },
  { id: 38, name: "龙祥时代" },
  { id: 46, name: "魅力足球" },
  { id: 57, name: "私人影院" },
  { id: 58, name: "东森电影" },
  { id: 59, name: "东森洋片" },
  { id: 61, name: "中国电影" },
  { id: 62, id2: 85, name: "天映经典" },
  { id: 139, name: "广东珠江" },
];
//广州电信酒店源
const GDGZ_HOTEL_TMPL = [
  { name: "广东卫视", id: 1 },
  { name: "广东珠江", id: 2 },
  { name: "广东新闻", id: 3 },
  { name: "广东公共", id: 4 },
  { name: "广东体育", id: 5 },
  { name: "广东国际", id: 6 },
  { name: "广东经济科教", id: 7 },
  { name: "南方卫视", id: 8 },
  { name: "广东影视", id: 9 },
  { name: "广东综艺", id: 10 },
  { name: "广东少儿", id: 11 },
  { name: "嘉佳卡通", id: 12 },
  { name: "广东房产", id: 13 },
  { name: "岭南戏曲", id: 14 },
  { name: "CCTV1", id: 15 },
  { name: "CCTV2", id: 16 },
  { name: "CCTV3", id: 17 },
  { name: "CCTV4", id: 18 },
  { name: "CCTV5", id: 19 },
  { name: "CCTV6", id: 20 },
  { name: "CCTV7", id: 21 },
  { name: "CCTV8", id: 22 },
  { name: "CCTV9", id: 23 },
  { name: "CCTV10", id: 24 },
  { name: "CCTV11", id: 25 },
  { name: "CCTV12", id: 26 },
  { name: "CCTV13", id: 27 },
  { name: "CCTV14", id: 28 },
  { name: "CCTV15", id: 29 },
  { name: "湖南卫视", id: 30 },
  { name: "浙江卫视", id: 31 },
  { name: "江苏卫视", id: 32 },
  { name: "东方卫视", id: 33 },
  { name: "安徽卫视", id: 34 },
  { name: "北京卫视", id: 35 },
  { name: "天津卫视", id: 36 },
  { name: "山东教育卫视", id: 37 },
  { name: "山东卫视", id: 38 },
  { name: "江西卫视", id: 39 },
  { name: "深圳卫视", id: 40 },
  { name: "湖北卫视", id: 41 },
  { name: "辽宁卫视", id: 42 },
  { name: "黑龙江卫视", id: 43 },
  { name: "贵州卫视", id: 44 },
  { name: "四川卫视", id: 45 },
  { name: "河南卫视", id: 46 },
  { name: "云南卫视", id: 47 },
  { name: "重庆卫视", id: 48 },
  { name: "河北卫视", id: 49 },
  { name: "东南卫视", id: 50 },
  { name: "广西卫视", id: 51 },
  { name: "吉林卫视", id: 52 },
  { name: "陕西卫视", id: 53 },
  { name: "山西卫视", id: 54 },
  { name: "内蒙古卫视", id: 55 },
  { name: "青海卫视", id: 56 },
  { name: "海南卫视", id: 57 },
  { name: "宁夏卫视", id: 58 },
  { name: "西藏卫视", id: 59 },
  { name: "新疆卫视", id: 60 },
  { name: "甘肃卫视", id: 61 },
  { name: "兵团卫视", id: 62 },
  { name: "金鹰卡通", id: 63 },
  { name: "哈哈炫动", id: 64 },
  { name: "未知", id: 65 },
  { name: "广东卫视HD", id: 70 },
  { name: "广东经济科教HD", id: 71 },
  { name: "广东珠江HD", id: 72 },
  { name: "CCTV1HD", id: 73 },
  { name: "CCTV2HD", id: 74 },
  { name: "CCTV3HD", id: 75 },
  { name: "CCTV5HD", id: 76 },
  { name: "CCTV6HD", id: 77 },
  { name: "CCTV7HD", id: 78 },
  { name: "CCTV8HD", id: 79 },
  { name: "CCTV9HD", id: 80 },
  { name: "CCTV10HD", id: 81 },
  { name: "CCTV12HD", id: 82 },
  { name: "CCTV14HD", id: 83 },
  { name: "CCTV5+HD", id: 84 },
  { name: "CCTV5HD", id: 85 },
  { name: "江苏卫视HD", id: 86 },
  { name: "深圳卫视HD", id: 87 },
  { name: "黑龙江卫视HD", id: 88 },
  { name: "湖北卫视HD", id: 89 },
  { name: "天津卫视HD", id: 90 },
  { name: "山东卫视HD", id: 91 },
  { name: "东方卫视HD", id: 92 },
  { name: "辽宁卫视HD", id: 93 },
  { name: "四川卫视HD", id: 94 },
  { name: "金鹰纪实HD", id: 95 },
  { name: "重庆卫视HD", id: 96 },
  { name: "安徽卫视HD", id: 97 },
  { name: "贵州卫视HD", id: 98 },
  { name: "未知", id: 99 },
  { name: "喜粤TV-极K影视", id: 100 },
  { name: "CHC高清电影", id: 110 },
  { name: "DOXTV", id: 111 },
  { name: "未知", id: 112 },
  { name: "广州新闻", id: 114 },
  { name: "广州影视", id: 115 },
  { name: "江门综合", id: 130 },
  { name: "江门公共", id: 131 },
  { name: "惠州综合", id: 132 },
  { name: "惠州公共", id: 133 },
  { name: "佛山公共", id: 134 },
];
//ip模板
const HOTEL_IPS = [
  { ip: "113.64.147.x", name: "揭阳电信113", idKey: "id" },
  { ip: "120.84.96.x", name: "揭阳联通120", idKey: "id2" },
  { ip: "27.47.68.x", name: "揭阳联通27-68" },
  { ip: "27.47.70.x", name: "揭阳联通27-70" },
  { ip: "27.47.71.x", name: "揭阳联通27-71", port: 8088 },
  { ip: "116.11.140.x", name: "玉林电信116", tmpl: GDJY_HOTEL_TMPL },
  { ip: "171.110.62.x", name: "玉林电信171", tmpl: GDJY_HOTEL_TMPL },
];

module.exports = {
  GDJY_HOTEL_TMPL,
  HOTEL_IPS,
};
